/* Generated by           cobc 2.0.0 */
/* Generated from         app.cbl */
/* Generated at           Mar 06 2020 22:56:45 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -x -o bin\app.exe -std=default -Wall -debug -g -free app.cbl */

/* Program local variables for 'Clock' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_1;	/* RETURN-CODE */
static cob_u8_t	b_7[22] __attribute__((aligned));	/* HELLO */
static cob_u8_t	b_8[8] __attribute__((aligned));	/* current-time */

/* End of data storage */


/* Fields */
static cob_field f_8	= {8, b_8, &a_1};	/* current-time */
static cob_field f_9	= {2, b_8, &a_4};	/* ct-hours */
static cob_field f_10	= {2, b_8 + 2, &a_4};	/* ct-minutes */
static cob_field f_11	= {2, b_8 + 4, &a_4};	/* ct-seconds */

/* End of fields */

