/* Generated by           cobc 2.0.0 */
/* Generated from         app.cbl */
/* Generated at           Mar 06 2020 22:56:45 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -x -o bin\app.exe -std=default -Wall -debug -g -free app.cbl */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"app.cbl"
#define  COB_PACKAGE_VERSION		"2.0"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Mar 06 2020 22:56:45"
#define  COB_MODULE_DATE		20200306
#define  COB_MODULE_TIME		225645

/* Global variables */
#include "app.c.h"

/* Function prototypes */

static int		Clock ();
static int		Clock_ (const int);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (Clock ());
}

/* Functions */

/* PROGRAM-ID 'Clock' */

/* ENTRY 'Clock' */

static int
Clock ()
{
  return Clock_ (0);
}

static int
Clock_ (const int entry)
{
  /* Program local variables */
  #include "app.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  cob_module_enter (&module, &cob_glob_ptr, 0);

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 20        : Entry     Clock                   : app.cbl */
  l_2:;
  cob_trace_section (st_2, st_1, 20);
  cob_trace_section (st_3, st_1, 20);

  /* Line: 20        : Paragraph MAIN-PROCEDURE          : app.cbl */
  cob_trace_section (st_4, st_1, 20);

  /* Line: 21        : Paragraph MAIN-PARA               : app.cbl */
  cob_trace_section (st_5, st_1, 21);

  /* Line: 24        : ACCEPT             : app.cbl */
  cob_set_location (st_1, 24, NULL, st_6, st_7);
  cob_accept_time (&f_8);

  /* Line: 27        : GO TO              : app.cbl */
  cob_set_location (st_1, 27, NULL, st_6, st_8);
  goto l_6;

  /* Line: 28        : STOP RUN           : app.cbl */
  cob_set_location (st_1, 28, NULL, st_6, st_9);
  cob_stop_run (b_1);

  /* Line: 30        : Paragraph LOOP-TIME-PARA          : app.cbl */
  l_6:;
  cob_trace_section (st_10, st_1, 30);

  /* Line: 31        : ACCEPT             : app.cbl */
  cob_set_location (st_1, 31, NULL, st_11, st_7);
  cob_accept_time (&f_8);

  /* Line: 32        : CALL               : app.cbl */
  cob_set_location (st_1, 32, NULL, st_11, st_12);
  cob_glob_ptr->cob_call_params = 0;
  b_1 = cob_sys_clear_screen ();

  /* Line: 33        : DISPLAY            : app.cbl */
  cob_set_location (st_1, 33, NULL, st_11, st_13);
  cob_field_display ((cob_field *)&c_1, (cob_field *)&c_2, (cob_field *)&c_3, (cob_field *)&c_3, NULL, NULL, NULL, 0);

  /* Line: 34        : IF                 : app.cbl */
  cob_set_location (st_1, 34, NULL, st_11, st_14);
  if (((int)cob_cmp_numdisp (b_8, 2, 12LL, 0) >= 0))
  {

    /* Line: 35        : SUBTRACT           : app.cbl */
    cob_set_location (st_1, 35, NULL, st_11, st_15);
    cob_check_numeric (&f_9, "ct-hours");
    cob_sub_int (&f_9, 12, 0);

    /* Line: 36        : DISPLAY            : app.cbl */
    cob_set_location (st_1, 36, NULL, st_11, st_13);
    cob_field_display (&f_9, (cob_field *)&c_3, (cob_field *)&c_3, (cob_field *)&c_3, NULL, NULL, NULL, 0);

    /* Line: 37        : DISPLAY            : app.cbl */
    cob_set_location (st_1, 37, NULL, st_11, st_13);
    cob_field_display ((cob_field *)&c_4, (cob_field *)&c_3, (cob_field *)&c_5, (cob_field *)&c_3, NULL, NULL, NULL, 0);

    /* Line: 38        : DISPLAY            : app.cbl */
    cob_set_location (st_1, 38, NULL, st_11, st_13);
    cob_field_display (&f_10, (cob_field *)&c_3, (cob_field *)&c_6, (cob_field *)&c_3, NULL, NULL, NULL, 0);

    /* Line: 39        : DISPLAY            : app.cbl */
    cob_set_location (st_1, 39, NULL, st_11, st_13);
    cob_field_display ((cob_field *)&c_4, (cob_field *)&c_3, (cob_field *)&c_7, (cob_field *)&c_3, NULL, NULL, NULL, 0);

    /* Line: 40        : DISPLAY            : app.cbl */
    cob_set_location (st_1, 40, NULL, st_11, st_13);
    cob_field_display (&f_11, (cob_field *)&c_3, (cob_field *)&c_8, (cob_field *)&c_3, NULL, NULL, NULL, 0);

    /* Line: 41        : DISPLAY            : app.cbl */
    cob_set_location (st_1, 41, NULL, st_11, st_13);
    cob_field_display ((cob_field *)&c_9, (cob_field *)&c_3, (cob_field *)&c_10, (cob_field *)&c_3, NULL, NULL, NULL, 0);
  }
  else
  {
    /* ELSE */

    /* Line: 43        : IF                 : app.cbl */
    cob_set_location (st_1, 43, NULL, st_11, st_14);
    if (((int)cob_cmp_numdisp (b_8, 2, 0LL, 0) == 0))
    {

      /* Line: 44        : ADD                : app.cbl */
      cob_set_location (st_1, 44, NULL, st_11, st_16);
      cob_check_numeric (&f_9, "ct-hours");
      cob_add_int (&f_9, 12, 0);
    }

    /* Line: 46        : DISPLAY            : app.cbl */
    cob_set_location (st_1, 46, NULL, st_11, st_13);
    cob_field_display (&f_9, (cob_field *)&c_3, (cob_field *)&c_3, (cob_field *)&c_3, NULL, NULL, NULL, 0);

    /* Line: 47        : DISPLAY            : app.cbl */
    cob_set_location (st_1, 47, NULL, st_11, st_13);
    cob_field_display ((cob_field *)&c_4, (cob_field *)&c_3, (cob_field *)&c_5, (cob_field *)&c_3, NULL, NULL, NULL, 0);

    /* Line: 48        : DISPLAY            : app.cbl */
    cob_set_location (st_1, 48, NULL, st_11, st_13);
    cob_field_display (&f_10, (cob_field *)&c_3, (cob_field *)&c_6, (cob_field *)&c_3, NULL, NULL, NULL, 0);

    /* Line: 49        : DISPLAY            : app.cbl */
    cob_set_location (st_1, 49, NULL, st_11, st_13);
    cob_field_display ((cob_field *)&c_4, (cob_field *)&c_3, (cob_field *)&c_7, (cob_field *)&c_3, NULL, NULL, NULL, 0);

    /* Line: 50        : DISPLAY            : app.cbl */
    cob_set_location (st_1, 50, NULL, st_11, st_13);
    cob_field_display (&f_11, (cob_field *)&c_3, (cob_field *)&c_8, (cob_field *)&c_3, NULL, NULL, NULL, 0);

    /* Line: 51        : DISPLAY            : app.cbl */
    cob_set_location (st_1, 51, NULL, st_11, st_13);
    cob_field_display ((cob_field *)&c_11, (cob_field *)&c_3, (cob_field *)&c_10, (cob_field *)&c_3, NULL, NULL, NULL, 0);
  }

  /* Line: 54        : CALL               : app.cbl */
  cob_set_location (st_1, 54, NULL, st_11, st_12);
  cob_procedure_params[0] = (cob_field *)&c_12;
  cob_glob_ptr->cob_call_params = 1;
  b_1 = cob_sys_oc_nanosleep ((cob_u8_ptr)"1000000000");

  /* Line: 55        : GO TO              : app.cbl */
  cob_set_location (st_1, 55, NULL, st_11, st_8);
  goto l_6;

  /* Line: 56        : STOP RUN           : app.cbl */
  cob_set_location (st_1, 56, NULL, st_11, st_9);
  cob_stop_run (b_1);

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Trace program exit */
  cob_trace_section (st_17, NULL, 0);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_1;

  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  /* Initialize module structure */
  module->module_name = "Clock";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())Clock;
  module->module_cancel.funcptr = (void *(*)())Clock_;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_1 = 0;
  memcpy (b_7, "Hello from COBOL!", 17);
  memset (b_7 + 17, 32, 5);
  memset (b_8, 48, 8);

  initialized = 1;
  goto P_ret_initialize;

  /* CANCEL callback handling */
  P_cancel:

  if (!initialized) {
  	return 0;
  }
  if (module->module_active) {
  	cob_fatal_error (COB_FERROR_CANCEL);
  }

  initialized = 0;
  return 0;

}

/* End PROGRAM-ID 'Clock' */

/* End functions */

