/* Generated by           cobc 2.0.0 */
/* Generated from         app.cbl */
/* Generated at           Mar 06 2020 22:56:45 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -x -o bin\app.exe -std=default -Wall -debug -g -free app.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   1,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x10,   2,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {19, (cob_u8_ptr)"The current time is", &a_2};
static const cob_field c_2	= {1, (cob_u8_ptr)"1", &a_3};
static const cob_field c_3	= {1, (cob_u8_ptr)"2", &a_3};
static const cob_field c_4	= {1, (cob_u8_ptr)":", &a_2};
static const cob_field c_5	= {1, (cob_u8_ptr)"4", &a_3};
static const cob_field c_6	= {1, (cob_u8_ptr)"5", &a_3};
static const cob_field c_7	= {1, (cob_u8_ptr)"7", &a_3};
static const cob_field c_8	= {1, (cob_u8_ptr)"8", &a_3};
static const cob_field c_9	= {2, (cob_u8_ptr)"PM", &a_2};
static const cob_field c_10	= {2, (cob_u8_ptr)"11", &a_4};
static const cob_field c_11	= {2, (cob_u8_ptr)"AM", &a_2};
static const cob_field c_12	= {10, (cob_u8_ptr)"1000000000", &a_2};


/* Strings */
static const char st_1[]	= "app.cbl";
static const char st_2[]	= "Entry:     Clock";
static const char st_3[]	= "Section:   (None)";
static const char st_4[]	= "Paragraph: MAIN-PROCEDURE";
static const char st_5[]	= "Paragraph: MAIN-PARA";
static const char st_6[]	= "MAIN-PARA";
static const char st_7[]	= "ACCEPT";
static const char st_8[]	= "GO TO";
static const char st_9[]	= "STOP RUN";
static const char st_10[]	= "Paragraph: LOOP-TIME-PARA";
static const char st_11[]	= "LOOP-TIME-PARA";
static const char st_12[]	= "CALL";
static const char st_13[]	= "DISPLAY";
static const char st_14[]	= "IF";
static const char st_15[]	= "SUBTRACT";
static const char st_16[]	= "ADD";
static const char st_17[]	= "Exit:      Clock";

